[package]
name = "sbb_parse"
version = "0.1.0"
authors = ["Pantonshire <tom@tomandtally.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
unicode-segmentation = "1.7"
