[package]
name = "sbb_data"
version = "0.1.0"
authors = ["Tom Panton <pantonshire@gmail.com>"]
edition = "2018"

[dependencies]
diesel = { version = "1.4", features = ["postgres", "chrono"] }
dotenv = "0.15"
chrono = "0.4"
